administration/urls.py
from django.urls import path
from .views import send_verification_email
from django.contrib.auth.views import PasswordChangeView
from django.urls import path
from django.contrib.auth.decorators import login_required
from django.urls import path
from .views import simple_password_change, verify_account
from django.contrib.auth import views as auth_views

from academic.forms import MaterialCreateForm
from academic.views import MaterialUpdateView, MaterialDeleteView, MaterialDetailView
from .views import CourseView, MaterialView, MemberView, MemberCreateView, MemberUpdateView, MemberDeleteView, \
    MemberDetailView, CourseCreateView, CourseUpdateView, CourseDeleteView, CourseDetailView, MaterialCreateView, ModuleListView, \
    ModuleDetailView,ModuleCreateView,ModuleUpdateView,ModuleDeleteView

# from administration.views import member_profile
urlpatterns = [
    # path('member/', member_profile, name='member_profile'),
    path('course/', CourseView.as_view(), name='course'),
    path('material/', MaterialView.as_view(), name='material'),
    path('member/', MemberView.as_view(), name='member'),
    path('member/create', MemberCreateView.as_view(), name='create_member'),
    path('member/update/<str:pk>', MemberUpdateView.as_view(), name='update_member'),
    path('member/delete/<str:pk>', MemberDeleteView.as_view(), name='delete_member'),
    path('member/detail/<str:pk>', MemberDetailView.as_view(), name='view_member'),
    path('course/create', CourseCreateView.as_view(), name='create_course'),
    path('course/update/<str:pk>/', CourseUpdateView.as_view(), name='update_course'),
    path('course/delete/<str:pk>/', CourseDeleteView.as_view(), name='delete_course'),
    path('course/detail/<str:pk>/', CourseDetailView.as_view(), name='view_course'),
    path('material/create', MaterialCreateView.as_view(), name='create_material'),
    path('material/update/<str:pk>/', MaterialUpdateView.as_view(), name='update_material'),
    path('material/delete/<str:pk>/', MaterialDeleteView.as_view(), name='delete_material'),
    path('material/detail/<str:pk>/', MaterialDetailView.as_view(), name='view_material'),
    path('verify-account/<int:member_id>/', verify_account, name='verify_account'),
    path('modules/', ModuleListView.as_view(), name='module'),
    path('modules/<int:pk>/', ModuleDetailView.as_view(), name='module_detail'),
    path('modules/add/', ModuleCreateView.as_view(), name='module_add'),
    path('modules/<int:pk>/edit/', ModuleUpdateView.as_view(), name='module_edit'),
    path('modules/<int:pk>/delete/', ModuleDeleteView.as_view(), name='module_delete'),
    path('password-change-direct/', simple_password_change, name='simple_password_change'),
    path(
        'password-reset/',
        auth_views.PasswordResetView.as_view(template_name='registration/password_reset_form.html'),
        name='password_reset',
    ),
    path(
        'password-reset/done/',
        auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'),
        name='password_reset_done',
    ),
    path(
        'password-reset-confirm/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'),
        name='password_reset_confirm',
    ),
    path(
        'password-reset-complete/',
        auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
        name='password_reset_complete',
    ),

]


ctmis/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import include, path
from ctmis.settings import MEDIA_URL, MEDIA_ROOT, STATIC_URL, STATIC_ROOT, DEBUG
from administration.views import send_verification_email  # Import the view for sending emails
# additional imports for AWS static files configurations
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')),
    path('', lambda request: redirect('auth/login/', permanent=False)),
    path('ctmis/', include([
        path('dashboard/', include('dashboard.urls')),
        path('academic/', include('academic.urls')),
        path('finance/', include('finance.urls')),
        path('administration/', include('administration.urls')),
    ])),
    # Add the route for sending emails
    path('send-email/<int:member_id>/', send_verification_email, name='send-email'),
]

urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

if DEBUG:
    urlpatterns += static(STATIC_URL, document_root=STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_URL)

administration/models.py
from django.db import models

# Create your models here.

database/models.py
from django.contrib.auth.models import User
from django.db import models

class Member(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    first_name = models.CharField(max_length=100)
    middle_name = models.CharField(max_length=100, blank=True, null=True)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(blank=True, null=True)
    phone_number = models.CharField(max_length=20)
    email = models.EmailField()
    physical_address = models.TextField()
    place_of_domicile = models.CharField(max_length=100)
    current_place_of_residency = models.CharField(max_length=100)
    year_of_study = models.PositiveIntegerField()
    course = models.CharField(max_length=100)
    ministry = models.CharField(max_length=100)
    current_place_of_worship = models.CharField(max_length=100)
    previous_place_of_worship = models.CharField(max_length=100, blank=True, null=True)
    next_of_kin = models.CharField(max_length=200)
    image = models.ImageField(upload_to='member_images/', blank=True, null=True)
    sex = models.CharField(max_length=100)
    role = models.CharField(max_length=100)

    def __str__(self):
        return f'{self.first_name} {self.middle_name}, {self.last_name}'

     
     
class Course(models.Model):
    course_code = models.CharField(max_length=20)
    name = models.CharField(max_length=100)
     
    def __str__(self):
        #  return "{}: {}".format(self.course_code, self.name)
        return f'{self.course_code}, {self.name}'
    
     
class Module(models.Model):
    name = models.CharField(max_length=100)
    semester = models.CharField(max_length=50)
    course = models.ManyToManyField(Course)
    year = models.PositiveIntegerField(null=True, blank=True)
     
    def __str__(self):
        return f'{self.name}'
       
class Material(models.Model):
    CATEGORY_CHOICES = (
        ('Lecture Notes', 'Lecture Notes'),
        ('Assignments', 'Assignments'),
        ('Reference Materials', 'Reference Materials'),
        ('Other', 'Other'),
    )

    name = models.CharField(max_length=200) 
    category = models.CharField(max_length=50, choices=CATEGORY_CHOICES)
    file = models.FileField(upload_to='materials/')
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    module = models.ForeignKey(Module, on_delete=models.CASCADE)
    
    def __str__(self):
        return f'{self.name}: {self.category}'

class MaterialCategory(models.Model):
    name = models.CharField(max_length=50)
    
    def __str__(self):
        return f'{self.name}'




class Revenue(models.Model):
    contribution = models.ForeignKey('Contribution', on_delete=models.CASCADE)
    amount = models.PositiveIntegerField(null=True, blank=True)
    description = models.TextField()

    def __str__(self):
        return f'{self.contribution}: {self.amount}: {self.description}'

class Expenditure(models.Model):
    date = models.DateField()  
    creditor_name = models.CharField(max_length=100)
    amount = models.PositiveIntegerField(null=True, blank=True)
    description = models.TextField()
    
    def __str__(self):
        return f'{self.date}: {self.creditor_name}:{self.amount}: {self.description}'
    
class FeeStructure(models.Model):
    fee_type = models.CharField(max_length=100)
    amount = models.PositiveIntegerField(null=True, blank=True)

    def __str__(self):
        return f'{self.fee_type}  {self.amount}'

class FeeSummary(models.Model):
    fee_type = models.CharField(max_length=100)
    amount_paid = models.PositiveIntegerField(null=True, blank=True)
    total_amount = models.PositiveIntegerField(null=True, blank=True)
    debit = models.PositiveIntegerField(null=True, blank=True)

    def __str__(self):
        return f'{self.fee_type} {self.amount_paid} {self.total_amount} {self.debt}'
    

class Contribution(models.Model):
    PAYMENT_STATUS_CHOICES = [
        ('full', 'Full-paid'),
        ('half', 'Half-paid'),
    ]
    
    member = models.ForeignKey(Member, on_delete=models.CASCADE, related_name='contributions')
    name = models.ForeignKey(FeeStructure, on_delete=models.CASCADE, related_name='type')
    description = models.CharField(max_length=10, choices=PAYMENT_STATUS_CHOICES, default='half')
    amount = models.DecimalField(max_digits=10, decimal_places=2)  # Assuming contributions have an amount
    date = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return f'{self.name}: {self.description} - {self.amount} - {self.date}'

class Receipt(models.Model):
    contribution = models.OneToOneField(Contribution, on_delete=models.CASCADE, related_name='receipt')
    member = models.ForeignKey(Member, on_delete=models.CASCADE, related_name='receipts')
    receipt_code = models.CharField(max_length=20, unique=False)
    date = models.DateField(auto_now_add=True)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    description = models.TextField()
    recorder_name = models.CharField(max_length=100)

    def save(self, *args, **kwargs):
        # Automatically set amount and description from the related contribution
        if self.contribution:
            self.amount = self.contribution.amount
            self.description = f"{self.contribution.name}: {self.contribution.description}"
        super().save(*args, **kwargs)

    def __str__(self):
        return f"Receipt {self.receipt_code} for Contribution {self.contribution.id}"

class Voucher(models.Model):
    voucher_code = models.CharField(max_length=20, unique=False)
    approval_date = models.DateField(auto_now_add=True)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    description = models.TextField()
    Approved_by = models.CharField(max_length=100)

    def __str__(self):
        return f"Voucher {self.voucher_code} - {self.amount}"


administration/forms.py
from django import forms
from django.contrib.auth.models import User


class SimplePasswordChangeForm(forms.Form):
    new_password1 = forms.CharField(
        widget=forms.PasswordInput(attrs={'placeholder': 'New Password'}),
        label="New Password"
    )
    new_password2 = forms.CharField(
        widget=forms.PasswordInput(attrs={'placeholder': 'Confirm New Password'}),
        label="Confirm Password"
    )

    def clean(self):
        cleaned_data = super().clean()
        password1 = cleaned_data.get("new_password1")
        password2 = cleaned_data.get("new_password2")

        if password1 != password2:
            raise forms.ValidationError("Passwords do not match.")
        return cleaned_data



from database.models import Member, Course, Material
class MemberCreateForm(forms.ModelForm):
    class Meta:
        model = Member
        fields = '__all__'

class CourseCreateForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = '__all__'

class MaterialCreateForm(forms.ModelForm):
    class Meta:
        model = Material
        fields = '__all__'



class MemberCreateForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput, required=False)  # Allow blank if updating

    class Meta:
        model = Member
        fields = ['first_name', 'middle_name', 'last_name', 'date_of_birth', 'phone_number', 'email', 'physical_address', 'place_of_domicile', 'current_place_of_residency', 'year_of_study', 'course', 'ministry', 'current_place_of_worship', 'previous_place_of_worship', 'next_of_kin', 'image', 'sex', 'role']
        exclude = ['user']  # The user is handled in the view, not directly in the form

password = forms.CharField(widget=forms.PasswordInput)

def save(self, commit=True):
        member = super().save(commit=False)
        
        # Create the user object here
        user = User(
            username=member.first_name,  # or any other field as username
            email=member.email,
            is_active=True
        )
        user.set_password(self.cleaned_data['password'])  # Hashing the password
        
        if commit:
            user.save()
            member.user = user  # Associate the member with the user
            member.save()
        
        return member

templates/administration/course_create_form.html
{% extends "base_child.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block breadcrumb %}
    <li class="breadcrumb-item">{{ module_title }}</li>
    <li class="breadcrumb-item">{{ page_title }}</li>
{% endblock %}
{% block page_content %}
    <form action="{% url 'create_course' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Delete Course Form</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            {{ form | crispy }}
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
            <button type="submit" class="btn btn-primary">Add</button>
        </div>
    </form>
{% endblock %}

templates/administration/course_detail_form.html
<!-- course_detail.html -->
{% extends "base_child.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block breadcrumb %}
<li class="breadcrumb-item">{{ module_title }}</li>
<li class="breadcrumb-item">{{ page_title }}</li>
{% endblock %}

{% block page_content %}
<div class="modal-header">
    <h5 class="modal-title" id="exampleModalLabel">{{ course.name }}</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<div class="modal-body">
    <p><strong>Course Code:</strong> {{ course.course_code }}</p>
    <p><strong>Course Name:</strong> {{ course.name }}</p>
    <!-- Add more fields as needed -->
</div>
<div class="modal-footer">
    <a href="{% url 'update_course' course.pk %}" class="btn btn-primary">Edit</a>
    <a href="{% url 'delete_course' course.pk %}" class="btn btn-danger">Delete</a>
</div>
{% endblock %}

templates/administration/course_update_form.html
{% extends "base_child.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block breadcrumb %}
    <li class="breadcrumb-item">{{ module_title }}</li>
    <li class="breadcrumb-item">{{ page_title }}</li>
{% endblock %}
{% block page_content %}
    <form action="{% url 'update_course' course.pk %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Update course Form</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            {{ form | crispy }}
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
            <button type="submit" class="btn btn-primary">Save</button>
        </div>
    </form>
{% endblock %}

templates/administration/material_delete_form.html
<!-- course_delete_form.html -->
{% extends "base_child.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block breadcrumb %}
    <li class="breadcrumb-item">{{ module_title }}</li>
    <li class="breadcrumb-item">{{ page_title }}</li>
{% endblock %}
{% block page_content %}
    <form action="{% url 'delete_material' material.pk %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Delete Material</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <p>Are you sure you want to delete this material?</p>
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Name</th>
                        <th>Course</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>{{ course.id }}</td>
                        <td>{{ course.name }}</td>
                        <td>{{ course.course }}</td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
            <button type="submit" class="btn btn-danger">Delete</button>
        </div>
    </form>
{% endblock %}

templates/administration/material_detail_form.html
<!-- course_detail.html -->
{% extends "base_child.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block breadcrumb %}
<li class="breadcrumb-item">{{ module_title }}</li>
<li class="breadcrumb-item">{{ page_title }}</li>
{% endblock %}

{% block page_content %}
<div class="modal-header">
    <h5 class="modal-title" id="exampleModalLabel">{{ material.name }}</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<div class="modal-body">
    <p><strong>Material Name:</strong> {{ material.name }}</p>
    <p><strong>Course Name:</strong> {{ material.course }}</p>
    <!-- Add more fields as needed -->
</div>
<div class="modal-footer">
    <a href="{% url 'update_material' material.pk %}" class="btn btn-primary">Edit</a>
    <a href="{% url 'delete_material' material.pk %}" class="btn btn-danger">Delete</a>
</div>
{% endblock %}

templates/administration/material_update_form.html
{% extends "base_child.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block breadcrumb %}
    <li class="breadcrumb-item">{{ module_title }}</li>
    <li class="breadcrumb-item">{{ page_title }}</li>
{% endblock %}
{% block page_content %}
    <form action="{% url 'update_material' material.pk %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Update material Form</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            {{ form | crispy }}
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
            <button type="submit" class="btn btn-primary">Save</button>
        </div>
    </form>
{% endblock %}

templates/administration/member.html
{% extends "base_child.html" %}
{% load custom_tags %}

{% if request.user|has_group:"ADMINS" %}

 {% load static %}
 {% load crispy_forms_tags %}
 {% block breadcrumb %}
 <li class="breadcrumb-item">{{ module_title }}</li>
 <li class="breadcrumb-item">{{ page_title }}</li>
 {% endblock %}
 {% block page_content %}
 <div class="table-responsive row">
    <table class="table table-bordered table-hover" id="dt-member">
        <thead class="thread-default thread-lg">
            <tr>
                <th>ID</th>
                <th>Firstname</th>
                <th>Lastname</th>
                <th>Course</th>
                <th>Year</th>
                <th class="no-sort" style="width:200px"></th>
            </tr>
        </thead>
        <tbody>
            {% for member in member_list %}
            <tr>
                <td>{{ member.id }}</td>
                <td>{{ member.first_name }}</td>
                <td>{{ member.last_name }}</td>
                <td>{{ member.course }}</td>
                <td>{{ member.year_of_study }}</td>
                <td>
                    <a href="{% url 'view_member' member.id %}" class="btn btn-primary btn-sm">View</a>
                    <a href="{% url 'update_member' member.id %}" class="btn btn-primary btn-sm">Edit</a>
                    <a href="{% url 'delete_member' member.id %}" class="btn btn-primary btn-sm">Delete</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
 </div>

 <!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <form action="{% url 'create_member' %}" method="post">
                {% csrf_token %}
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">New Member Form</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    {{ material_form|crispy }}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>
            </form>
        </div>
    </div>
 </div>
 {% comment %} <div>
    {% if member %}
    <h2>Member Profile</h2>
    
    <p><strong>First Name:</strong> {{ member.first_name }}</p>
    <p><strong>Middle Name:</strong> {{ member.middle_name }}</p>
    <p><strong>Last Name:</strong> {{ member.last_name }}</p>
    <p><strong>Date of Birth:</strong> {{ member.date_of_birth }}</p>
    <p><strong>Phone Number:</strong> {{ member.phone_number }}</p>
    <p><strong>Email:</strong> {{ member.email }}</p>
    <p><strong>Physical Address:</strong> {{ member.physical_address }}</p>
    <p><strong>Place of Domicile:</strong> {{ member.place_of_domicile }}</p>
    <p><strong>Current Place of Residency:</strong> {{ member.current_place_of_residency }}</p>
    <p><strong>Year of Study:</strong> {{ member.year_of_study }}</p>
    <p><strong>Course:</strong> {{ member.course }}</p>
    <p><strong>Ministry:</strong> {{ member.ministry }}</p>
    <p><strong>Current Place of Worship:</strong> {{ member.current_place_of_worship }}</p>
    <p><strong>Previous Place of Worship:</strong> {{ member.previous_place_of_worship }}</p>
    <p><strong>Next of Kin:</strong> {{ member.next_of_kin }}</p>
    <p><strong>Sex:</strong> {{ member.sex }}</p>
    <p><strong>Role:</strong> {{ member.role }}</p>
{% else %}
    <p>No member profile found for this user.</p>
{% endif %}

 </div> {% endcomment %}

 {% endblock %}

 {% block page_scripts %}
 <script>
    $(function () {
        $('#dt-member').DataTable({
            pageLength: 10,
            fixedHeader: true,
            responsive: true,
            "sDom": "<'d-flex mb-1 justify-content-between'<'#table-search'f><'#table-length'l><'#table-buttons'B><'#custom-buttons'>>" +
                "<'d-flex'tr>" +
                "<'d-flex justify-content-between'ip>",
            columnDefs: [{
                targets: 'no-sort',
                orderable: false
            }],
        });
        $('#custom-buttons').html('<a href="{% url "create_member" %}" type="button" class="btn btn-primary">Add Member</a>');
    });
</script>


  {% endblock %}
{% endif %}


{% comment %} >>> from django.contrib.auth.models import User
>>> from database.models import Member
>>> user = User.objects.get(username='princemfinanga@gmail.com')
>>> member = Member.objects.filter(user=user).first()
>>> print(member)
Prince Noah, mfinanga
>>> {% endcomment %}

templates/administration/member_create_form.html
{% extends "base_child.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block breadcrumb %}
    <li class="breadcrumb-item">{{ module_title }}</li>
    <li class="breadcrumb-item">{{ page_title }}</li>
{% endblock %}
{% block page_content %}
    <form action="{% url 'create_member' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">New Member Form</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            {{ form | crispy }}
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
            <button type="submit" class="btn btn-primary">Save</button>
        </div>
    </form>
{% endblock %}

templates/administration/member_delete_form.html
<!-- course_delete_form.html -->
{% extends "base_child.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block breadcrumb %}
    <li class="breadcrumb-item">{{ module_title }}</li>
    <li class="breadcrumb-item">{{ page_title }}</li>
{% endblock %}
{% block page_content %}
    <form action="{% url 'delete_member' member.pk %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Delete Member</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <p>Are you sure you want to delete this member?</p>
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Firstname</th>
                        <th>Lastname</th>
                        <th>Course</th>
                        <th>Year</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>{{ member.id }}</td>
                        <td>{{ member.first_name }}</td>
                        <td>{{ member.last_name }}</td>
                        <td>{{ member.course }}</td>
                        <td>{{ member.year }}</td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
            <button type="submit" class="btn btn-danger">Delete</button>
        </div>
    </form>
{% endblock %}

templates/administration/member_detail_form.html
<!-- course_detail.html -->
{% extends "base_child.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block breadcrumb %}
<li class="breadcrumb-item">{{ module_title }}</li>
<li class="breadcrumb-item">{{ page_title }}</li>
{% endblock %}

{% block page_content %}
<div class="modal-header">
    <h5 class="modal-title" id="exampleModalLabel">{{ member.first_name }}</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<div class="modal-body">
    <p><strong>Firstname:</strong> {{ member.last_name }}</p>
    <p><strong>Course Name:</strong> {{ member.course }}</p>
    <!-- Add more fields as needed -->
</div>
<div class="modal-footer">
    <a href="{% url 'update_member' member.pk %}" class="btn btn-primary">Edit</a>
    <a href="{% url 'delete_member' member.pk %}" class="btn btn-danger">Delete</a>
</div>
{% endblock %}

templates/administration/member_update_form.html
{% extends "base_child.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block breadcrumb %}
    <li class="breadcrumb-item">{{ module_title }}</li>
    <li class="breadcrumb-item">{{ page_title }}</li>
{% endblock %}
{% block page_content %}
    <form action="{% url 'update_member' member.pk %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Update Member Form</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            {{ form | crispy }}
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
            <button type="submit" class="btn btn-primary">Save</button>
        </div>
    </form>
{% endblock %}